source 'https://github.com/CocoaPods/Specs.git'

# ignore all warnings from all pods
inhibit_all_warnings!

use_frameworks!
platform :ios, '11.0'

# workaround for https://github.com/CocoaPods/CocoaPods/issues/8073
# need for correct invalidate of cache MultiPlatformLibrary.framework
install! 'cocoapods', :disable_input_output_paths => true

target 'TestProj' do
  pod 'R.swift', '5.1.0'
  # MultiPlatformLibrary
  pod 'MultiPlatformLibrary', :path => '../mpp-library'
  pod 'MultiPlatformLibraryUnits/Core', :git => 'https://github.com/icerockdev/moko-units.git', :tag => 'release/0.2.0-dev-2'
  pod 'MultiPlatformLibraryUnits/R.swift', :git => 'https://github.com/icerockdev/moko-units.git', :tag => 'release/0.2.0-dev-2'
end
